version: '3'
services:
  database:
    image: mongo
    container_name: mongo-container
    environment:
      - MONGO_INITDB_DATABASE=test
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017-27019:27017-27019
